### PR TITLE
BCM2708/ASoC: Add Mbed audio board support

### PR DESCRIPTION
**Pull request by kfigiela**
(Almost) copy-paste merge from 3.8 branch.

### CODE REVIEW

**Comment by koalo** [comment]
Thank you!
Have you tested it?

**Comment by kfigiela** [comment]
Yes, it is working fine :) 

The only issue is that I get some DMA warnings in `dmesg`, but playback still works:

```
[ 4364.432611] bcm2708-dmaengine bcm2708-dmaengine: DMA transfer could not be terminated
```

**Comment by kfigiela** [comment]
I'm not sure why github shows here my another commit, but this one (d16f542) shouldn't be merged.

**Comment by koalo** [comment]
Github adds commits to the pull request as long as you push them to the same branch and the pull request is not merged, yet. The DMA error seems like a bug in my DMA driver - I will have a look at it.

**Comment by koalo** [comment]
Could you please try to increase the timeout in this line:
https://github.com/koalo/linux/blob/rpi-3.10.y/drivers/dma/bcm2708-dmaengine.c#L380

E.g. to 10000

**Comment by kfigiela** [comment]
I've increased timeout to 10 000 and no warnings so far. I will give you more feedback on that tomorrow evening.

**Comment by kfigiela** [comment]
Ok, no warnings after whole day. Increasing the timeout fixed the issue.

**Comment by koalo** [comment]
Thank you very much for reporting and testing!

**Comment by koalo** [comment]
Regarding the original request: I haven't merged this, because I was about to submit the driver to raspberrypi/linux. Please rebase it and submit the pull request there.

**Comment by kfigiela** [comment]
Ok, will do it next week.

**Pull request closed without merging**
