### PR TITLE
ASoC: Add support for PCM5102A

### PR DESCRIPTION
**Pull request by WallaceIT**
Add support for PCM5102A codec from TI; the driver is a rework of ESS9018 driver with the addition of 24bit audio capability

### CODE REVIEW

**Comment by maximus21** [comment]
I don't think this is the place to add codecs that should go into mainstream linux

**Comment by WallaceIT** [comment]
The pull request includes RPi drivers as well...

**Comment by maximus21** [comment]
the DAC has only 2 channels, not 8.
the modules were not written by Florian.

**Comment by WallaceIT** [comment]
You are right, I forgot to put my name on the modules. Going to edit them. Thanks

**Comment by koalo** [comment]
It is the right place - as WallaceIT said, it includes all the bindings for the Raspberry Pi. The driver alone might be useable for mainstream linux, but since it includes only a few definitions, I would postpone this until the I2S driver itself is upstream.

I am looking forward to your corrected version.

**Pull request closed without merging**
